spring:
  application:
    name: stock-service
  cloud:
    config:
      name: stock
      profile: deploy
  config:
    import: "optional:configserver:http://140.83.85.62:8888"

eureka:
  client:
    service-url:
      defaultZone: http://140.83.85.62:8761/eureka/
  instance:
    hostname: 140.83.85.62