spring:
  application:
    name: stock-service
  cloud:
    config:
      name: stock
      profile: deploy
  config:
    import: "optional:configserver:http://13.237.183.108:8888"

eureka:
  client:
    service-url:
      defaultZone: http://13.237.183.108:8761/eureka/
  instance:
    hostname: 13.237.183.108