spring:
  application:
    name: payment-service
  cloud:
    config:
      name: payment
      profile: deploy
  config:
    import: "optional:configserver:http://152.69.232.209:8888"


eureka:
  client:
    service-url:
      defaultZone: http://152.69.232.209:8761/eureka/
  instance:
    hostname: 152.69.232.209

#encrypt:
#  key : ${ENCRYPT_KEY}