spring:
  application:
    name: payment-service
  cloud:
    config:
      name: payment
      profile: deploy
#    bus:
#      enabled: true
#  kafka:
#    bootstrap-servers: 152.69.232.209:9092

  config:
    import: "optional:configserver:http://13.237.183.108:8888"

eureka:
  client:
    service-url:
      defaultZone: http://13.237.183.108:8761/eureka/
  instance:
    hostname: 13.237.183.108

#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh

#encrypt:
#  key : ${ENCRYPT_KEY}