spring:
  application:
    name: payment-service
  cloud:
    config:
      name: payment
      profile: deploy
#    bus:
#      enabled: true
#  kafka:
#    bootstrap-servers: 152.69.232.209:9092

  config:
    import: "optional:configserver:http://140.83.85.62:8888"

eureka:
  client:
    service-url:
      defaultZone: http://140.83.85.62:8761/eureka/
  instance:
    hostname: 140.83.85.62

#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh

#encrypt:
#  key : ${ENCRYPT_KEY}